Fix #175: Add testcase for multibyte LikeHandler
yiisoft/data pull request #190
Opened 2024-09-07 16:03 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

2024-09-07 17:28 UTC, arogachev approved these changes

2024-09-07 17:34 UTC, vjik requested changes
Need a line in changelog

2024-09-07 22:31 UTC, samdark commented
There's no change for end user at all so I doubt changelog is needed.

2024-09-08 09:10 UTC, samdark commented
Added CHANGELOG.

2024-09-08 09:27 UTC, vjik approved these changes

2024-09-08 09:27 UTC, vjik commented on CHANGELOG.md
> +- Chg #190: Add testcase for multibyte `LikeHandler`, use `str_contains` for case-sensitive match (@samdark)
```suggestion
- Enh #190: Use `str_contains` for case-sensitive match in `LikeHandler` (@samdark) 
```

2024-09-08 09:59 UTC, merged