Fix #187: Respect DataReader limit in paginators
yiisoft/data pull request #191
Opened 2024-09-07 18:07 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️

2024-09-08 08:54 UTC, vjik requested changes

2024-09-08 08:54 UTC, vjik commented on src/Reader/Iterable/IterableDataReader.php
> +    private ?int $limit = null;
Let's do the same with offset?

2024-09-08 08:54 UTC, vjik commented on src/Reader/FilterableDataInterface.php
>      public function withFilter(FilterInterface $filter): static;
```suggestion
    public function withFilter(?FilterInterface $filter): static;
```

2024-09-08 08:54 UTC, vjik commented on README.md
> +- The limit set in the data reader is ignored
```suggestion
- The limit set in the data reader leads to throw exception
```

2024-09-08 08:54 UTC, vjik commented on src/Paginator/KeysetPaginator.php
> + * - The limit set in the data reader is ignored
```suggestion
 * - The limit set in the data reader leads to throw exception
```

2024-09-08 08:54 UTC, vjik commented on src/Paginator/OffsetPaginator.php
Check edge case when limit is 0 and call `readOne`.

2024-09-08 09:01 UTC, vjik commented on src/Paginator/OffsetPaginator.php
> +            $limit = $this->getOffset() + $this->pageSize - $dataReaderLimit;
Seems, here should be `$dataReaderLimit - $this->getOffset()`.

For example:
- data reader limit is 14
- page size is 5
- page is 3

Offset = 5 * (3 - 1) = 10
Condition is true: 10 + 5 > 14
Limit = 10 + 5 - 14 = 1 (incorrect, must be 4)

2024-09-08 09:27 UTC, samdark commented on src/Reader/Iterable/IterableDataReader.php
> +    private ?int $limit = null;
No. https://postgrespro.com/docs/postgresql/9.4/queries-limit:

> OFFSET says to skip that many rows before beginning to return rows. **OFFSET 0 is the same as omitting the OFFSET clause, and LIMIT NULL is the same as omitting the LIMIT clause**.

2024-09-08 09:28 UTC, samdark commented on src/Reader/Iterable/IterableDataReader.php
> +    private ?int $limit = null;
https://dev.mysql.com/doc/refman/8.4/en/limit-optimization.html:

> **LIMIT 0 quickly returns an empty set**. This can be useful for checking the validity of a query. It can also be employed to obtain the types of the result columns within applications that use a MySQL API that makes result set metadata available.

2024-09-08 09:50 UTC, samdark commented
@vjik good comments. Fixed.

2024-09-08 14:46 UTC, vjik requested changes
Looks good 👍 Need to kill mutants only.

2024-09-09 17:31 UTC, samdark commented
@vjik I think I need help with it.

2024-09-10 17:50 UTC, vjik approved these changes

2024-09-10 17:50 UTC, merged