Add more test cases for `Like`
yiisoft/data pull request #198
Opened 2024-09-26 15:40 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

2024-10-01 14:01 UTC, vjik requested changes

2024-10-01 14:01 UTC, vjik commented on tests/Common/Reader/ReaderWithFilter/BaseReaderWithLikeTestCase.php
> +            'case does not match, contains search string, case sensitive: null' => ['email', 'SEED@', null, [2]],
```suggestion
            'case matches, contains search string, case sensitive: null' => ['email', 'SEED@', null, [2]],
```

Also need tests when case sensitice is true and case does not match.

2024-10-01 14:31 UTC, samdark approved these changes

2024-10-03 10:11 UTC, vjik approved these changes

2024-10-03 10:35 UTC, merged