Disable sort when limit is explicit
yiisoft/data pull request #201
Opened 2024-09-29 11:58 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

2024-09-29 17:50 UTC, vjik requested changes

2024-09-29 17:50 UTC, vjik commented on .gitignore
> +.phpunit.result.cache
```suggestion
```

Not need for PhpUnit 10+

2024-09-29 17:50 UTC, vjik commented on src/Paginator/KeysetPaginator.php
Keyset paginator doesn't take into account limit in data reader. Seems, it's not requires changes.

2024-09-29 17:50 UTC, vjik commented on src/Paginator/OffsetPaginator.php
Add line to changelog.

2024-09-29 17:50 UTC, vjik commented on src/Paginator/OffsetPaginator.php
> +        if ($this->dataReader instanceof LimitableDataInterface && $this->dataReader->getLimit() !== null) {
I think, it's not need, because get current sort for non-sortable data reader (with limit) is OK.

2024-10-17 21:01 UTC, samdark commented on src/Paginator/KeysetPaginator.php
> +        }
Keyset paginator can not work without sorting. Does that mean that limit can't be applied at all?

2024-10-17 21:03 UTC, samdark commented on src/Paginator/KeysetPaginator.php
> +        return !($this->dataReader instanceof LimitableDataInterface && $this->dataReader->getLimit() !== null);
Keyset paginator can't be non-sortable, right @vjik ?

2024-10-18 12:49 UTC, vjik commented on src/Paginator/KeysetPaginator.php
> +        return !($this->dataReader instanceof LimitableDataInterface && $this->dataReader->getLimit() !== null);
Yes.

2024-10-18 20:49 UTC, samdark commented on tests/Paginator/OffsetPaginatorTest.php
> +        $this->expectException(InvalidArgumentException::class);
Not sure it worth changing exception type.

2024-10-18 21:11 UTC, samdark commented
Applied suggestions and fixed some additional stuff.

2024-10-19 15:30 UTC, vjik requested changes
What about similar fixes in `KeysetPaginator`?

2024-10-19 15:30 UTC, vjik commented on src/Paginator/OffsetPaginator.php
> +            throw new InvalidArgumentException('Data reader does not support sorting.');
Argument is correct. Suggest keep `LogicException`, it's notifying the user to fix his code.

2024-10-19 15:30 UTC, vjik commented on src/Paginator/OffsetPaginator.php
> +        /** @psalm-suppress UndefinedInterfaceMethod */
```suggestion
```

Add `@psalm-assert-if-true SortableDataInterface $this->dataReader` annotation to `isSortable()` method.

2024-10-19 15:30 UTC, vjik commented on src/Paginator/OffsetPaginator.php
> +        /** @psalm-suppress UndefinedInterfaceMethod */
```suggestion
```

Add `@psalm-assert-if-true FilterableDataInterface $this->dataReader` annotation to `isFiltarable()` method.

2024-10-19 15:30 UTC, vjik commented on src/Paginator/OffsetPaginator.php
> +            throw new InvalidArgumentException('Data reader does not support filtering.');
Argument is correct, but logic of paginator usage in user code is broken. Suggest keep `LogicException`, it's notifying the user to fix his code.

2024-10-20 10:56 UTC, samdark commented
@vjik good suggestions. Applied.

2024-10-21 08:11 UTC, vjik approved these changes

2024-10-21 08:11 UTC, merged