Fix key set paginator
yiisoft/data pull request #44
Opened 2020-08-30 12:01 UTC by romkatsu

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #43 

I don't really like this decision. There was also an option to accept callbale.
What do you think about this decision?

2020-08-30 12:23 UTC, roxblnfk requested changes

2020-08-30 12:23 UTC, roxblnfk commented on src/Paginator/KeysetPaginator.php
> +        if (is_object($item) && method_exists($item, $getterName)) {
```suggestion
        if (is_object($item) && is_callable([$item, $getterName])) {
```
https://3v4l.org/JGgoM

2020-08-30 12:23 UTC, roxblnfk commented on src/Paginator/KeysetPaginator.php
> +    private function getGetterName(string $field): string
I think that there is no need to allocate a separate method for this

2020-08-30 12:25 UTC, romkatsu commented on src/Paginator/KeysetPaginator.php
> +        if (is_object($item) && method_exists($item, $getterName)) {
fixed

2020-08-30 12:25 UTC, romkatsu commented on src/Paginator/KeysetPaginator.php
> +    private function getGetterName(string $field): string
remove

2020-08-30 12:59 UTC, samdark approved these changes

2020-08-30 17:05 UTC, roxblnfk approved these changes

2020-08-31 09:35 UTC, hiqsol approved these changes

2020-08-31 23:56 UTC, merged

2020-08-31 23:56 UTC, samdark commented
👍