Add getSort() in OffserPaginator::class.
yiisoft/data pull request #74
Opened 2021-02-12 16:03 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2021-02-12 19:09 UTC, samdark requested changes

2021-02-12 19:09 UTC, samdark commented on src/Paginator/OffsetPaginator.php
> +    public function getSort(): ?Sort
I think it should be added to `PaginatorInterface` as well, right?

2021-02-12 19:11 UTC, terabytesoftw commented on src/Paginator/OffsetPaginator.php
> +    public function getSort(): ?Sort
👍

2021-02-12 22:12 UTC, roxblnfk requested changes

2021-02-12 23:12 UTC, samdark commented on src/Paginator/OffsetPaginator.php
> +        return $this->dataReader->getSort();
Else return null, yes.

2021-02-24 11:10 UTC, terabytesoftw commented on src/Paginator/OffsetPaginator.php
> +    public function getSort(): ?Sort
done.

2021-02-24 14:46 UTC, merged

2021-02-24 14:46 UTC, samdark commented
👍