Add filters of Between, EqualsEmpty and EqualsNull
yiisoft/data pull request #85
Opened 2022-02-14 13:50 UTC by devanych

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #42

2022-02-14 14:08 UTC, samdark approved these changes

2022-02-14 14:08 UTC, samdark commented on src/Reader/Filter/Between.php
> +                gettype($value),
Here it is a good idea to specify class name if the value is a class.

2022-02-14 14:16 UTC, merged

2022-02-14 14:16 UTC, samdark commented
👍

2022-02-15 15:21 UTC, roxblnfk requested changes

2022-02-15 15:21 UTC, roxblnfk commented on src/Reader/Filter/Between.php
> +            throw new InvalidArgumentException(sprintf(
What about datetimeInterface?
Is it possible to support this?

2022-02-15 15:21 UTC, roxblnfk commented on src/Reader/Iterable/Processor/EqualsEmpty.php
> +        return empty($item[$field]);
This checking can be incorrect for the value `"0"`.

2022-02-15 15:21 UTC, roxblnfk commented on tests/Reader/Iterable/Processor/EqualsEmptyTest.php
> +            [true, ['value' => 0.0]],
Need to add "0"

2022-02-15 16:40 UTC, samdark commented on src/Reader/Filter/Between.php
> +            throw new InvalidArgumentException(sprintf(
Yes, that would be great. @roxblnfk would you please add an issue about it?

2022-02-16 20:01 UTC, devanych commented on src/Reader/Filter/Between.php
> +            throw new InvalidArgumentException(sprintf(
In the same filter? Or can create a separate `BetweenDate` class?

2022-02-16 20:02 UTC, devanych commented on tests/Reader/Iterable/Processor/EqualsEmptyTest.php
> +            [true, ['value' => 0.0]],
Done.

2022-02-17 09:31 UTC, devanych commented on src/Reader/Filter/Between.php
> +            throw new InvalidArgumentException(sprintf(
https://github.com/yiisoft/data/issues/88