Add DateTimeInterface support to some filters and processors
yiisoft/data pull request #92
Opened 2022-02-23 08:12 UTC by devanych

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | -

2022-03-27 08:17 UTC, vjik requested changes

2022-03-27 08:17 UTC, vjik commented on tests/TestCase.php
> +            'float' => [1,1],
```suggestion
            'float' => [1.1],
```

2022-03-27 11:18 UTC, terabytesoftw approved these changes

2022-03-30 19:41 UTC, samdark approved these changes

2022-03-30 19:42 UTC, merged

2022-03-30 19:42 UTC, samdark commented
👍